# Generated by Django 4.1.5 on 2023-01-24 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_url", models.URLField(max_length=50)),
                ("short_url", models.URLField(max_length=20)),
                (
                    "transition_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("transition_count", models.IntegerField()),
            ],
        ),
    ]
