# Generated by Django 4.1.5 on 2023-01-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("short_link", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Urls",
            fields=[
                (
                    "short_url_id",
                    models.SlugField(max_length=6, primary_key=True, serialize=False),
                ),
                ("long_url", models.URLField(max_length=2000)),
                ("transition_date", models.DateTimeField(auto_now=True)),
                ("transition_count", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
