# Generated by Django 4.1.5 on 2023-01-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("short_link", "0002_urls_delete_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urls",
            name="transition_count",
            field=models.IntegerField(default=0),
        ),
    ]
